language: ruby
notifications:
  email:
    on_success: change
    on_failure: always

before_install:
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - gem install bundler
  - bundle --version
  - mkdir -p tmp/bundle

bundler_args: "--binstubs"

rvm: 
  # - 1.8.7 - include below so RUBYGEMS version gets set
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode
  - rbx-2.2.6
  - jruby-head
  - ruby-head
  - rbx

script: bin/rake build spec install

matrix:
  allow_failures:
    # error: sqlite3-1.3.9/lib/sqlite3/sqlite3_native.so: undefined symbol: RBIGNUM_DIGITS
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: rbx
  include:
    # set RUBYGEMS_VERSION=1.8.25 for ruby 1.8.7 to avoid "undefined method `source_index' for Gem:Module" errors
    - rvm: 1.8.7
      env: RUBYGEMS_VERSION=1.8.25

